/**
 * Canonical GTMI Methodology V1
 * Note: Keep this file in parity with docs/METHODOLOGY.md manually.
 * This is the source-of-truth for the extraction pipeline and scoring engine.
 */

export const methodologyV1 = {
  framework_structure: {
    A: {
      'A.1': ['A.1.1', 'A.1.2', 'A.1.3'],
      'A.2': ['A.2.1', 'A.2.2', 'A.2.3'],
      'A.3': ['A.3.1', 'A.3.2', 'A.3.3'],
    },
    B: {
      'B.1': ['B.1.1', 'B.1.2', 'B.1.3'],
      'B.2': ['B.2.1', 'B.2.2', 'B.2.3', 'B.2.4'],
      'B.3': ['B.3.1', 'B.3.2', 'B.3.3'],
    },
    C: {
      'C.1': ['C.1.1', 'C.1.2', 'C.1.3', 'C.1.4'],
      'C.2': ['C.2.1', 'C.2.2', 'C.2.3', 'C.2.4'],
      'C.3': ['C.3.1', 'C.3.2'],
    },
    D: {
      'D.1': ['D.1.1', 'D.1.2', 'D.1.3', 'D.1.4'],
      'D.2': ['D.2.1', 'D.2.2', 'D.2.3', 'D.2.4'],
      'D.3': ['D.3.1', 'D.3.2', 'D.3.3'],
    },
    E: {
      'E.1': ['E.1.1', 'E.1.2', 'E.1.3'],
      'E.2': ['E.2.1', 'E.2.2', 'E.2.3'],
      'E.3': ['E.3.1', 'E.3.2'],
    },
  },
  pillar_weights: { A: 0.28, B: 0.15, C: 0.2, D: 0.22, E: 0.15 },
  sub_factor_weights: {
    'A.1': 0.4,
    'A.2': 0.35,
    'A.3': 0.25,
    'B.1': 0.4,
    'B.2': 0.35,
    'B.3': 0.25,
    'C.1': 0.45,
    'C.2': 0.35,
    'C.3': 0.2,
    'D.1': 0.5,
    'D.2': 0.35,
    'D.3': 0.15,
    'E.1': 0.5,
    'E.2': 0.3,
    'E.3': 0.2,
  },
  indicator_weights: {
    'A.1.1': 0.5,
    'A.1.2': 0.3,
    'A.1.3': 0.2,
    'A.2.1': 0.35,
    'A.2.2': 0.35,
    'A.2.3': 0.3,
    'A.3.1': 0.4,
    'A.3.2': 0.35,
    'A.3.3': 0.25,
    'B.1.1': 0.5,
    'B.1.2': 0.3,
    'B.1.3': 0.2,
    'B.2.1': 0.4,
    'B.2.2': 0.25,
    'B.2.3': 0.2,
    'B.2.4': 0.15,
    'B.3.1': 0.4,
    'B.3.2': 0.35,
    'B.3.3': 0.25,
    'C.1.1': 0.3,
    'C.1.2': 0.3,
    'C.1.3': 0.25,
    'C.1.4': 0.15,
    'C.2.1': 0.4,
    'C.2.2': 0.25,
    'C.2.3': 0.2,
    'C.2.4': 0.15,
    'C.3.1': 0.5,
    'C.3.2': 0.5,
    'D.1.1': 0.3,
    'D.1.2': 0.3,
    'D.1.3': 0.2,
    'D.1.4': 0.2,
    'D.2.1': 0.3,
    'D.2.2': 0.3,
    'D.2.3': 0.2,
    'D.2.4': 0.2,
    'D.3.1': 0.36,
    'D.3.2': 0.44,
    'D.3.3': 0.2,
    'E.1.1': 0.5,
    'E.1.2': 0.3,
    'E.1.3': 0.2,
    'E.2.1': 0.4,
    'E.2.2': 0.3,
    'E.2.3': 0.3,
    'E.3.1': 0.5,
    'E.3.2': 0.5,
  },
  normalization_choices: {
    'A.1.1': 'z_score',
    'A.1.2': 'min_max',
    'A.1.3': 'categorical',
    'A.2.1': 'categorical',
    'A.2.2': 'min_max',
    'A.2.3': 'categorical',
    'A.3.1': 'categorical',
    'A.3.2': 'categorical',
    'A.3.3': 'min_max',
    'B.1.1': 'min_max',
    'B.1.2': 'categorical',
    'B.1.3': 'min_max',
    'B.2.1': 'z_score',
    'B.2.2': 'z_score',
    'B.2.3': 'z_score',
    'B.2.4': 'z_score',
    'B.3.1': 'categorical',
    'B.3.2': 'min_max',
    'B.3.3': 'categorical',
    'C.1.1': 'categorical',
    'C.1.2': 'categorical',
    'C.1.3': 'categorical',
    'C.1.4': 'boolean',
    'C.2.1': 'categorical',
    'C.2.2': 'min_max',
    'C.2.3': 'boolean',
    'C.2.4': 'boolean',
    'C.3.1': 'categorical',
    'C.3.2': 'categorical',
    'D.1.1': 'boolean',
    'D.1.2': 'min_max',
    'D.1.3': 'min_max',
    'D.1.4': 'min_max',
    'D.2.1': 'boolean',
    'D.2.2': 'min_max',
    'D.2.3': 'boolean',
    'D.2.4': 'categorical',
    'D.3.1': 'min_max',
    'D.3.2': 'categorical',
    'D.3.3': 'categorical',
    'E.1.1': 'z_score',
    'E.1.2': 'boolean',
    'E.1.3': 'min_max',
    'E.2.1': 'boolean',
    'E.2.2': 'categorical',
    'E.2.3': 'categorical',
    'E.3.1': 'min_max',
    'E.3.2': 'min_max',
  },
  cme_paq_split: { cme: 0.3, paq: 0.7 },
  version_tag: '1.0.0',
  indicators: [
    {
      key: 'A.1.1',
      label: 'Minimum salary threshold (USD-equivalent)',
      dataType: 'numeric',
      pillar: 'A',
      subFactor: 'A.1',
      weightWithinSubFactor: 0.5,
      extractionPromptMd:
        'TODO: Write prompt for A.1.1 - Minimum salary threshold (USD-equivalent)',
      scoringRubricJsonb: null,
      normalizationFn: 'z_score',
      direction: 'lower_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'A.1.2',
      label: 'Salary threshold as % of local median wage',
      dataType: 'numeric',
      pillar: 'A',
      subFactor: 'A.1',
      weightWithinSubFactor: 0.3,
      extractionPromptMd:
        'TODO: Write prompt for A.1.2 - Salary threshold as % of local median wage',
      scoringRubricJsonb: null,
      normalizationFn: 'min_max',
      direction: 'lower_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'A.1.3',
      label: 'Alternative qualification pathways (points, capital, patent)',
      dataType: 'categorical',
      pillar: 'A',
      subFactor: 'A.1',
      weightWithinSubFactor: 0.2,
      extractionPromptMd:
        'TODO: Write prompt for A.1.3 - Alternative qualification pathways (points, capital, patent)',
      scoringRubricJsonb: null,
      normalizationFn: 'categorical',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'A.2.1',
      label: 'Minimum educational requirement',
      dataType: 'categorical',
      pillar: 'A',
      subFactor: 'A.2',
      weightWithinSubFactor: 0.35,
      extractionPromptMd: 'TODO: Write prompt for A.2.1 - Minimum educational requirement',
      scoringRubricJsonb: null,
      normalizationFn: 'categorical',
      direction: 'lower_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'A.2.2',
      label: 'Minimum work experience (years)',
      dataType: 'numeric',
      pillar: 'A',
      subFactor: 'A.2',
      weightWithinSubFactor: 0.35,
      extractionPromptMd: 'TODO: Write prompt for A.2.2 - Minimum work experience (years)',
      scoringRubricJsonb: null,
      normalizationFn: 'min_max',
      direction: 'lower_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'A.2.3',
      label: 'Language proficiency requirement (level + acceptance list)',
      dataType: 'categorical',
      pillar: 'A',
      subFactor: 'A.2',
      weightWithinSubFactor: 0.3,
      extractionPromptMd:
        'TODO: Write prompt for A.2.3 - Language proficiency requirement (level + acceptance list)',
      scoringRubricJsonb: null,
      normalizationFn: 'categorical',
      direction: 'lower_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'A.3.1',
      label: 'Occupation list constraint (open / restricted list / shortage list)',
      dataType: 'categorical',
      pillar: 'A',
      subFactor: 'A.3',
      weightWithinSubFactor: 0.4,
      extractionPromptMd:
        'TODO: Write prompt for A.3.1 - Occupation list constraint (open / restricted list / shortage list)',
      scoringRubricJsonb: null,
      normalizationFn: 'categorical',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'A.3.2',
      label: 'Annual quota presence and size',
      dataType: 'categorical',
      pillar: 'A',
      subFactor: 'A.3',
      weightWithinSubFactor: 0.35,
      extractionPromptMd: 'TODO: Write prompt for A.3.2 - Annual quota presence and size',
      scoringRubricJsonb: null,
      normalizationFn: 'categorical',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'A.3.3',
      label: 'Applicant age cap',
      dataType: 'numeric',
      pillar: 'A',
      subFactor: 'A.3',
      weightWithinSubFactor: 0.25,
      extractionPromptMd: 'TODO: Write prompt for A.3.3 - Applicant age cap',
      scoringRubricJsonb: null,
      normalizationFn: 'min_max',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'B.1.1',
      label: 'Published SLA processing time (days)',
      dataType: 'numeric',
      pillar: 'B',
      subFactor: 'B.1',
      weightWithinSubFactor: 0.5,
      extractionPromptMd: 'TODO: Write prompt for B.1.1 - Published SLA processing time (days)',
      scoringRubricJsonb: null,
      normalizationFn: 'min_max',
      direction: 'lower_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'B.1.2',
      label: 'Fast-track option availability and SLA',
      dataType: 'categorical',
      pillar: 'B',
      subFactor: 'B.1',
      weightWithinSubFactor: 0.3,
      extractionPromptMd: 'TODO: Write prompt for B.1.2 - Fast-track option availability and SLA',
      scoringRubricJsonb: null,
      normalizationFn: 'categorical',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'B.1.3',
      label: 'Number of application steps',
      dataType: 'numeric',
      pillar: 'B',
      subFactor: 'B.1',
      weightWithinSubFactor: 0.2,
      extractionPromptMd: 'TODO: Write prompt for B.1.3 - Number of application steps',
      scoringRubricJsonb: null,
      normalizationFn: 'min_max',
      direction: 'lower_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'B.2.1',
      label: 'Principal applicant fees (USD)',
      dataType: 'numeric',
      pillar: 'B',
      subFactor: 'B.2',
      weightWithinSubFactor: 0.4,
      extractionPromptMd: 'TODO: Write prompt for B.2.1 - Principal applicant fees (USD)',
      scoringRubricJsonb: null,
      normalizationFn: 'z_score',
      direction: 'lower_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'B.2.2',
      label: 'Per-dependant fees (USD)',
      dataType: 'numeric',
      pillar: 'B',
      subFactor: 'B.2',
      weightWithinSubFactor: 0.25,
      extractionPromptMd: 'TODO: Write prompt for B.2.2 - Per-dependant fees (USD)',
      scoringRubricJsonb: null,
      normalizationFn: 'z_score',
      direction: 'lower_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'B.2.3',
      label: 'Employer-borne levies and skill charges (USD)',
      dataType: 'numeric',
      pillar: 'B',
      subFactor: 'B.2',
      weightWithinSubFactor: 0.2,
      extractionPromptMd:
        'TODO: Write prompt for B.2.3 - Employer-borne levies and skill charges (USD)',
      scoringRubricJsonb: null,
      normalizationFn: 'z_score',
      direction: 'lower_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'B.2.4',
      label: 'Mandatory non-government costs (agents, translation, medicals)',
      dataType: 'numeric',
      pillar: 'B',
      subFactor: 'B.2',
      weightWithinSubFactor: 0.15,
      extractionPromptMd:
        'TODO: Write prompt for B.2.4 - Mandatory non-government costs (agents, translation, medicals)',
      scoringRubricJsonb: null,
      normalizationFn: 'z_score',
      direction: 'lower_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'B.3.1',
      label: 'Online application availability',
      dataType: 'categorical',
      pillar: 'B',
      subFactor: 'B.3',
      weightWithinSubFactor: 0.4,
      extractionPromptMd: 'TODO: Write prompt for B.3.1 - Online application availability',
      scoringRubricJsonb: null,
      normalizationFn: 'categorical',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'B.3.2',
      label: 'In-person / biometric requirement (count of visits)',
      dataType: 'numeric',
      pillar: 'B',
      subFactor: 'B.3',
      weightWithinSubFactor: 0.35,
      extractionPromptMd:
        'TODO: Write prompt for B.3.2 - In-person / biometric requirement (count of visits)',
      scoringRubricJsonb: null,
      normalizationFn: 'min_max',
      direction: 'lower_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'B.3.3',
      label: 'Appeal and refusal process clarity',
      dataType: 'categorical',
      pillar: 'B',
      subFactor: 'B.3',
      weightWithinSubFactor: 0.25,
      extractionPromptMd: 'TODO: Write prompt for B.3.3 - Appeal and refusal process clarity',
      scoringRubricJsonb: null,
      normalizationFn: 'categorical',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'C.1.1',
      label: 'Employer-sponsorship requirement',
      dataType: 'categorical',
      pillar: 'C',
      subFactor: 'C.1',
      weightWithinSubFactor: 0.3,
      extractionPromptMd: 'TODO: Write prompt for C.1.1 - Employer-sponsorship requirement',
      scoringRubricJsonb: null,
      normalizationFn: 'categorical',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'C.1.2',
      label: 'Ability to switch employers (no re-application vs. re-application)',
      dataType: 'categorical',
      pillar: 'C',
      subFactor: 'C.1',
      weightWithinSubFactor: 0.3,
      extractionPromptMd:
        'TODO: Write prompt for C.1.2 - Ability to switch employers (no re-application vs. re-application)',
      scoringRubricJsonb: null,
      normalizationFn: 'categorical',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'C.1.3',
      label: 'Self-employment and secondary income rights',
      dataType: 'categorical',
      pillar: 'C',
      subFactor: 'C.1',
      weightWithinSubFactor: 0.25,
      extractionPromptMd:
        'TODO: Write prompt for C.1.3 - Self-employment and secondary income rights',
      scoringRubricJsonb: null,
      normalizationFn: 'categorical',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'C.1.4',
      label: 'Labor market test requirement',
      dataType: 'boolean',
      pillar: 'C',
      subFactor: 'C.1',
      weightWithinSubFactor: 0.15,
      extractionPromptMd: 'TODO: Write prompt for C.1.4 - Labor market test requirement',
      scoringRubricJsonb: null,
      normalizationFn: 'boolean',
      direction: 'lower_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'C.2.1',
      label: 'Spouse inclusion and work rights (automatic / by permit / none)',
      dataType: 'categorical',
      pillar: 'C',
      subFactor: 'C.2',
      weightWithinSubFactor: 0.4,
      extractionPromptMd:
        'TODO: Write prompt for C.2.1 - Spouse inclusion and work rights (automatic / by permit / none)',
      scoringRubricJsonb: null,
      normalizationFn: 'categorical',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'C.2.2',
      label: 'Dependent child age cap and inclusion terms',
      dataType: 'numeric',
      pillar: 'C',
      subFactor: 'C.2',
      weightWithinSubFactor: 0.25,
      extractionPromptMd:
        'TODO: Write prompt for C.2.2 - Dependent child age cap and inclusion terms',
      scoringRubricJsonb: null,
      normalizationFn: 'min_max',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'C.2.3',
      label: 'Parent or extended family inclusion option',
      dataType: 'boolean',
      pillar: 'C',
      subFactor: 'C.2',
      weightWithinSubFactor: 0.2,
      extractionPromptMd:
        'TODO: Write prompt for C.2.3 - Parent or extended family inclusion option',
      scoringRubricJsonb: null,
      normalizationFn: 'boolean',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'C.2.4',
      label: 'Same-sex partner recognition',
      dataType: 'boolean',
      pillar: 'C',
      subFactor: 'C.2',
      weightWithinSubFactor: 0.15,
      extractionPromptMd: 'TODO: Write prompt for C.2.4 - Same-sex partner recognition',
      scoringRubricJsonb: null,
      normalizationFn: 'boolean',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'C.3.1',
      label: 'Public healthcare access',
      dataType: 'categorical',
      pillar: 'C',
      subFactor: 'C.3',
      weightWithinSubFactor: 0.5,
      extractionPromptMd: 'TODO: Write prompt for C.3.1 - Public healthcare access',
      scoringRubricJsonb: null,
      normalizationFn: 'categorical',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'C.3.2',
      label: 'Public education access for children',
      dataType: 'categorical',
      pillar: 'C',
      subFactor: 'C.3',
      weightWithinSubFactor: 0.5,
      extractionPromptMd: 'TODO: Write prompt for C.3.2 - Public education access for children',
      scoringRubricJsonb: null,
      normalizationFn: 'categorical',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'D.1.1',
      label: 'PR provision available (yes / no)',
      dataType: 'boolean',
      pillar: 'D',
      subFactor: 'D.1',
      weightWithinSubFactor: 0.3,
      extractionPromptMd: 'TODO: Write prompt for D.1.1 - PR provision available (yes / no)',
      scoringRubricJsonb: null,
      normalizationFn: 'boolean',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'D.1.2',
      label: 'Minimum years of residence to PR eligibility',
      dataType: 'numeric',
      pillar: 'D',
      subFactor: 'D.1',
      weightWithinSubFactor: 0.3,
      extractionPromptMd:
        'TODO: Write prompt for D.1.2 - Minimum years of residence to PR eligibility',
      scoringRubricJsonb: null,
      normalizationFn: 'min_max',
      direction: 'lower_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'D.1.3',
      label: 'Physical presence requirement during accrual (days/yr)',
      dataType: 'numeric',
      pillar: 'D',
      subFactor: 'D.1',
      weightWithinSubFactor: 0.2,
      extractionPromptMd:
        'TODO: Write prompt for D.1.3 - Physical presence requirement during accrual (days/yr)',
      scoringRubricJsonb: null,
      normalizationFn: 'min_max',
      direction: 'lower_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'D.1.4',
      label: 'PR retention rules (days/yr to keep PR)',
      dataType: 'numeric',
      pillar: 'D',
      subFactor: 'D.1',
      weightWithinSubFactor: 0.2,
      extractionPromptMd: 'TODO: Write prompt for D.1.4 - PR retention rules (days/yr to keep PR)',
      scoringRubricJsonb: null,
      normalizationFn: 'min_max',
      direction: 'lower_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'D.2.1',
      label: 'Citizenship provision available from this track (yes / no)',
      dataType: 'boolean',
      pillar: 'D',
      subFactor: 'D.2',
      weightWithinSubFactor: 0.3,
      extractionPromptMd:
        'TODO: Write prompt for D.2.1 - Citizenship provision available from this track (yes / no)',
      scoringRubricJsonb: null,
      normalizationFn: 'boolean',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'D.2.2',
      label: 'Total minimum years from initial visa entry to citizenship eligibility',
      dataType: 'numeric',
      pillar: 'D',
      subFactor: 'D.2',
      weightWithinSubFactor: 0.3,
      extractionPromptMd:
        'TODO: Write prompt for D.2.2 - Total minimum years from initial visa entry to citizenship eligibility',
      scoringRubricJsonb: null,
      normalizationFn: 'min_max',
      direction: 'lower_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'D.2.3',
      label: 'Dual citizenship permitted',
      dataType: 'boolean',
      pillar: 'D',
      subFactor: 'D.2',
      weightWithinSubFactor: 0.2,
      extractionPromptMd: 'TODO: Write prompt for D.2.3 - Dual citizenship permitted',
      scoringRubricJsonb: null,
      normalizationFn: 'boolean',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'D.2.4',
      label: 'Civic / language / integration test burden',
      dataType: 'categorical',
      pillar: 'D',
      subFactor: 'D.2',
      weightWithinSubFactor: 0.2,
      extractionPromptMd:
        'TODO: Write prompt for D.2.4 - Civic / language / integration test burden',
      scoringRubricJsonb: null,
      normalizationFn: 'categorical',
      direction: 'lower_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'D.3.1',
      label: 'Tax residency trigger (days/yr before worldwide tax applies)',
      dataType: 'numeric',
      pillar: 'D',
      subFactor: 'D.3',
      weightWithinSubFactor: 0.36,
      extractionPromptMd:
        'TODO: Write prompt for D.3.1 - Tax residency trigger (days/yr before worldwide tax applies)',
      scoringRubricJsonb: null,
      normalizationFn: 'min_max',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'D.3.2',
      label: 'Special regime available (non-dom, expat bonus, flat-rate)',
      dataType: 'categorical',
      pillar: 'D',
      subFactor: 'D.3',
      weightWithinSubFactor: 0.44,
      extractionPromptMd:
        'TODO: Write prompt for D.3.2 - Special regime available (non-dom, expat bonus, flat-rate)',
      scoringRubricJsonb: null,
      normalizationFn: 'categorical',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'D.3.3',
      label: 'Territorial vs. worldwide taxation for residents',
      dataType: 'categorical',
      pillar: 'D',
      subFactor: 'D.3',
      weightWithinSubFactor: 0.2,
      extractionPromptMd:
        'TODO: Write prompt for D.3.3 - Territorial vs. worldwide taxation for residents',
      scoringRubricJsonb: null,
      normalizationFn: 'categorical',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'E.1.1',
      label: 'Material policy changes in last 5 years (count, weighted by severity)',
      dataType: 'numeric',
      pillar: 'E',
      subFactor: 'E.1',
      weightWithinSubFactor: 0.5,
      extractionPromptMd:
        'TODO: Write prompt for E.1.1 - Material policy changes in last 5 years (count, weighted by severity)',
      scoringRubricJsonb: null,
      normalizationFn: 'z_score',
      direction: 'lower_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'E.1.2',
      label: 'Forward-announced pipeline changes (positive predictability signal)',
      dataType: 'boolean',
      pillar: 'E',
      subFactor: 'E.1',
      weightWithinSubFactor: 0.3,
      extractionPromptMd:
        'TODO: Write prompt for E.1.2 - Forward-announced pipeline changes (positive predictability signal)',
      scoringRubricJsonb: null,
      normalizationFn: 'boolean',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'E.1.3',
      label: 'Program age (years since introduction, capped at 20)',
      dataType: 'numeric',
      pillar: 'E',
      subFactor: 'E.1',
      weightWithinSubFactor: 0.2,
      extractionPromptMd:
        'TODO: Write prompt for E.1.3 - Program age (years since introduction, capped at 20)',
      scoringRubricJsonb: null,
      normalizationFn: 'min_max',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'E.2.1',
      label: 'Published approval rate or admission statistics',
      dataType: 'boolean',
      pillar: 'E',
      subFactor: 'E.2',
      weightWithinSubFactor: 0.4,
      extractionPromptMd:
        'TODO: Write prompt for E.2.1 - Published approval rate or admission statistics',
      scoringRubricJsonb: null,
      normalizationFn: 'boolean',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'E.2.2',
      label: 'Published quota / cap information',
      dataType: 'categorical',
      pillar: 'E',
      subFactor: 'E.2',
      weightWithinSubFactor: 0.3,
      extractionPromptMd: 'TODO: Write prompt for E.2.2 - Published quota / cap information',
      scoringRubricJsonb: null,
      normalizationFn: 'categorical',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'E.2.3',
      label: 'Public guidance and decision criteria documentation',
      dataType: 'categorical',
      pillar: 'E',
      subFactor: 'E.2',
      weightWithinSubFactor: 0.3,
      extractionPromptMd:
        'TODO: Write prompt for E.2.3 - Public guidance and decision criteria documentation',
      scoringRubricJsonb: null,
      normalizationFn: 'categorical',
      direction: 'higher_is_better',
      sourceTierRequired: 1,
    },
    {
      key: 'E.3.1',
      label: 'Rule of law (V-Dem / World Bank WGI)',
      dataType: 'numeric',
      pillar: 'E',
      subFactor: 'E.3',
      weightWithinSubFactor: 0.5,
      extractionPromptMd: 'TODO: Write prompt for E.3.1 - Rule of law (V-Dem / World Bank WGI)',
      scoringRubricJsonb: null,
      normalizationFn: 'min_max',
      direction: 'higher_is_better',
      sourceTierRequired: 3,
    },
    {
      key: 'E.3.2',
      label: 'Government effectiveness (World Bank WGI)',
      dataType: 'numeric',
      pillar: 'E',
      subFactor: 'E.3',
      weightWithinSubFactor: 0.5,
      extractionPromptMd:
        'TODO: Write prompt for E.3.2 - Government effectiveness (World Bank WGI)',
      scoringRubricJsonb: null,
      normalizationFn: 'min_max',
      direction: 'higher_is_better',
      sourceTierRequired: 3,
    },
  ],
};
